### PR TITLE
Updated _nestable_block to work with newer streamlit version

### PR DESCRIPTION
**Pull request by XanX3601**
`streamlit-nested-layout` is not working anymore with `streamlit== 1.31.1` and maybe older versions because of `st.status` needs `dg_type` argument to work properly

### CODE REVIEW

**Comment by mkleinbort-ic** [comment]
I think this is fixed

**Comment by joy13975** [comment]
@XanX3601 so sorry I didn't see this PR. I didn't get email notification!
Anyway version `0.1.2` is up. It should have fixed your issues.

**Comment by XanX3601** [comment]
> @XanX3601 so sorry I didn't see this PR. I didn't get email notification! Anyway version `0.1.2` is up. It should have fixed your issues.

No problem, happy to see you fixed the situation :D

**Comment by XanX3601** [comment]
Pull request irrelevant because a fix has already been deployed for the same issue

**Pull request closed without merging**
